remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme 
title: [Tiny Digital Banned Book Library]
description: [This digital library hosts books that are being banned or challenged by Republicans - Conservatives - Fascists - and Christian Nationalists who are actively trying to ban information.]
